# Generated by Django 4.1 on 2022-08-21 18:06

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre_article', models.CharField(max_length=200)),
                ('slug_article', models.SlugField(max_length=200, null=True)),
                ('visuel_article', models.ImageField(blank=True, null=True, upload_to='visuel_article')),
                ('corps_article', models.TextField(blank=True)),
                ('date_creation_article', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_maj_article', models.DateTimeField(auto_now=True, null=True)),
                ('status_article', models.CharField(choices=[('brouillon', 'Brouillon'), ('publié', 'Publié')], default='brouillon', max_length=10)),
                ('publish', models.DateTimeField(default=datetime.datetime(2022, 8, 21, 18, 6, 56, 349947, tzinfo=datetime.timezone.utc))),
                ('auteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Categorie_oeuvre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_categorie_oeuvre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Citation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_citation', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Emotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_emotion', models.CharField(max_length=50)),
                ('visuel_emotion', models.ImageField(blank=True, upload_to='emotion')),
                ('definition_emotion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Oeuvre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_oeuvre', models.CharField(max_length=100)),
                ('synopsis_oeuvre', models.TextField(blank=True)),
                ('visuel_oeuvre', models.ImageField(blank=True, upload_to='visuel_oeuvre')),
                ('video_oeuvre', models.FileField(blank=True, null=True, upload_to='videos_oeuvre', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])])),
                ('categorie_oeuvre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.categorie_oeuvre')),
            ],
        ),
        migrations.CreateModel(
            name='Type_evenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_type_evenement', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Type_oeuvre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_type_oeuvre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Type_professionnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_type_professionnel', models.CharField(max_length=50)),
                ('explication_metier_professionnel', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Videotheque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_videotheque', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('voir', models.ManyToManyField(to='blog.oeuvre')),
            ],
        ),
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte_signature', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Professionnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom_professionnel', models.CharField(blank=True, max_length=50)),
                ('nom_professionnel', models.CharField(max_length=50)),
                ('date_naissance_professionnel', models.DateField(blank=True, null=True)),
                ('resume_carriere_professionnel', models.TextField(blank=True)),
                ('photo_professionnel', models.ImageField(blank=True, upload_to='photo_pro')),
                ('type_professionnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.type_professionnel')),
            ],
        ),
        migrations.AddField(
            model_name='oeuvre',
            name='professionnel',
            field=models.ManyToManyField(blank=True, to='blog.professionnel'),
        ),
        migrations.AddField(
            model_name='oeuvre',
            name='type_oeuvre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.type_oeuvre'),
        ),
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre_evenement', models.CharField(max_length=100)),
                ('visuel_evenement', models.ImageField(null=True, upload_to='visuel_evenement')),
                ('description_evenement', models.TextField(blank=True)),
                ('date_heure_evenement', models.DateTimeField(auto_now_add=True, null=True)),
                ('lieu_evenement', models.CharField(max_length=100)),
                ('organiser', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('type_evenement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.type_evenement')),
            ],
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_heure_commentaire', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('titre_commentaire', models.CharField(max_length=50)),
                ('corps_commentaire', models.TextField(blank=True)),
                ('commenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.article')),
            ],
        ),
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visuel_avatar', models.ImageField(upload_to='visuel_avatar')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='citer',
            field=models.ManyToManyField(blank=True, to='blog.citation'),
        ),
        migrations.AddField(
            model_name='article',
            name='oeuvrer',
            field=models.ManyToManyField(to='blog.oeuvre'),
        ),
        migrations.AddField(
            model_name='article',
            name='ressentir',
            field=models.ManyToManyField(blank=True, to='blog.emotion'),
        ),
    ]
