# Generated by Django 3.2.12 on 2022-04-04 12:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre_article', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='categorie_oeuvre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_categorie_oeuvre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='citation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_citation', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='emotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_emotion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='oeuvre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_oeuvre', models.CharField(max_length=100)),
                ('visuel_oeuvre', models.CharField(max_length=254)),
                ('video_oeuvre', models.CharField(blank=True, max_length=254)),
                ('categorie_oeuvre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.categorie_oeuvre')),
                ('citer', models.ManyToManyField(blank=True, to='blog.citation')),
            ],
        ),
        migrations.CreateModel(
            name='type_evenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_type_evenement', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='type_oeuvre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_type_oeuvre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='type_professionnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_type_professionnel', models.CharField(max_length=50)),
                ('explication_metier_professionnel', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='videotheque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_videotheque', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('voir', models.ManyToManyField(to='blog.oeuvre')),
            ],
        ),
        migrations.CreateModel(
            name='signature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='professionnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom_professionnel', models.CharField(blank=True, max_length=50)),
                ('nom_professionnel', models.CharField(max_length=50)),
                ('date_naissance_professionnel', models.DateField(blank=True)),
                ('resume_carriere_professionnel', models.TextField(blank=True)),
                ('photo_professionnel', models.CharField(max_length=254)),
                ('type_professionnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.type_professionnel')),
            ],
        ),
        migrations.AddField(
            model_name='oeuvre',
            name='professionnel',
            field=models.ManyToManyField(blank=True, to='blog.professionnel'),
        ),
        migrations.AddField(
            model_name='oeuvre',
            name='type_oeuvre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.type_oeuvre'),
        ),
        migrations.CreateModel(
            name='evenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre_evenement', models.CharField(max_length=100)),
                ('lieu_evenement', models.CharField(max_length=100)),
                ('organiser', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('type_evenement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.type_evenement')),
            ],
        ),
        migrations.CreateModel(
            name='commentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.article')),
            ],
        ),
        migrations.CreateModel(
            name='avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visuel_avatar', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='oeuvrer',
            field=models.ManyToManyField(to='blog.oeuvre'),
        ),
        migrations.AddField(
            model_name='article',
            name='ressentir',
            field=models.ManyToManyField(blank=True, to='blog.emotion'),
        ),
        migrations.AddField(
            model_name='article',
            name='utilisateur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
