# Generated by Django 3.2.12 on 2022-04-04 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oeuvre',
            name='citer',
        ),
        migrations.AddField(
            model_name='article',
            name='citer',
            field=models.ManyToManyField(blank=True, to='blog.citation'),
        ),
    ]
