# Generated by Django 3.2.12 on 2022-04-04 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20220404_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professionnel',
            name='photo_professionnel',
            field=models.CharField(blank=True, max_length=254),
        ),
    ]
