# Generated by Django 3.2.12 on 2022-04-04 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_professionnel_photo_professionnel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professionnel',
            name='date_naissance_professionnel',
            field=models.DateField(null=True),
        ),
    ]
