# Generated by Django 3.2.12 on 2022-04-04 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_professionnel_date_naissance_professionnel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oeuvre',
            name='visuel_oeuvre',
            field=models.CharField(blank=True, max_length=254),
        ),
    ]
