# Generated by Django 3.2.12 on 2022-04-05 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_oeuvre_visuel_oeuvre'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentaire',
            name='titre_commentaire',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
