# Generated by Django 3.2.12 on 2022-04-05 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_commentaire_titre_commentaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='corps_article',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='commentaire',
            name='corps_commentaire',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='commentaire',
            name='date_heure_commentaire',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='emotion',
            name='definition_emotion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='evenement',
            name='date_heure_evenement',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='evenement',
            name='description_evenement',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='oeuvre',
            name='synopsis_oeuvre',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='signature',
            name='texte_signature',
            field=models.TextField(blank=True),
        ),
    ]
