# Generated by Django 3.2.12 on 2022-04-05 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20220405_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='date_commentaire',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='commentaire',
            name='date_heure_commentaire',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
