# Generated by Django 3.2.12 on 2022-04-05 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20220405_1226'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='date_commentaire',
            new_name='date_article',
        ),
    ]
