# Generated by Django 3.2.12 on 2022-04-05 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_rename_date_commentaire_article_date_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date_article',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='commentaire',
            name='date_heure_commentaire',
            field=models.DateTimeField(null=True),
        ),
    ]
