# Generated by Django 3.2.12 on 2022-04-05 11:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20220405_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date_article',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='commentaire',
            name='date_heure_commentaire',
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
    ]
