# Generated by Django 4.1 on 2022-08-20 16:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20220405_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='date_article',
        ),
        migrations.AddField(
            model_name='article',
            name='date_creation_article',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='date_maj_article',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='slug_article',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='status_article',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('publié', 'Publié')], default='brouillon', max_length=10),
        ),
        migrations.AddField(
            model_name='article',
            name='visuel_article',
            field=models.ImageField(blank=True, null=True, upload_to='visuel_article'),
        ),
        migrations.AddField(
            model_name='emotion',
            name='visuel_emotion',
            field=models.ImageField(blank=True, upload_to='emotion'),
        ),
        migrations.AddField(
            model_name='evenement',
            name='visuel_evenement',
            field=models.ImageField(null=True, upload_to='visuel_evenement'),
        ),
        migrations.AlterField(
            model_name='article',
            name='titre_article',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='visuel_avatar',
            field=models.ImageField(upload_to='visuel_avatar'),
        ),
        migrations.AlterField(
            model_name='oeuvre',
            name='video_oeuvre',
            field=models.FileField(null=True, upload_to='videos_oeuvre', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])]),
        ),
        migrations.AlterField(
            model_name='oeuvre',
            name='visuel_oeuvre',
            field=models.ImageField(blank=True, upload_to='visuel_oeuvre'),
        ),
        migrations.AlterField(
            model_name='professionnel',
            name='photo_professionnel',
            field=models.ImageField(blank=True, upload_to='photo_pro'),
        ),
    ]
