# Generated by Django 4.1 on 2022-08-20 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_remove_article_date_article_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='utilisateur',
            new_name='auteur',
        ),
        migrations.AlterField(
            model_name='article',
            name='date_creation_article',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='date_maj_article',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
