# Generated by Django 4.1 on 2022-08-20 17:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_rename_utilisateur_article_auteur_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date_creation_article',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='date_maj_article',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='oeuvre',
            name='video_oeuvre',
            field=models.FileField(blank=True, null=True, upload_to='videos_oeuvre', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])]),
        ),
    ]
