# Generated by Django 4.1 on 2022-08-20 17:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_alter_article_date_creation_article_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 20, 17, 55, 39, 951517, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug_article',
            field=models.SlugField(max_length=200, null=True),
        ),
    ]
